### ISSUE TITLE
[BUG] Missing version constrains on dependencies

### ISSUE THREAD

**Issue by SEGVeenstra** [icyleaf/app-info#62]
<Mistake> Sorry

**Comment by SEGVeenstra** [comment]
Filled on wrong repo

**Comment by icyleaf** [comment]
Feel free to file any issue 😄

**Comment by SEGVeenstra** [comment]
Sure, but this was totally not related to your repo 😓 

I had two tabs open and in my haste I filled the issue on the wrong tab.

Friday-end-of-the-day-things
